/mnt/c/Users/marti/Desktop/school/dp/smt_cbs/loader.o /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/loader.or /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/loader.od /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/loader.op: /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/loader.cc \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/loader.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/SimpSolver.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/mtl/Queue.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/mtl/Vec.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/mtl/IntTypes.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/mtl/XAlloc.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/mtl/Clone.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/Solver.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/mtl/Heap.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/mtl/Alg.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/utils/Options.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/utils/../mtl/IntTypes.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/utils/../mtl/Vec.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/utils/ParseUtils.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/SolverTypes.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/../mtl/IntTypes.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/../mtl/Alg.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/../mtl/Vec.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/../mtl/Map.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/../mtl/../mtl/IntTypes.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/../mtl/../mtl/Vec.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/../mtl/Alloc.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/../mtl/XAlloc.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/../mtl/Vec.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/BoundedQueue.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/Constants.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/SolverStats.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/map.h
/mnt/c/Users/marti/Desktop/school/dp/smt_cbs/main.o /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/main.or /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/main.od /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/main.op: /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/main.cc \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/loader.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/SimpSolver.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/mtl/Queue.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/mtl/Vec.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/mtl/IntTypes.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/mtl/XAlloc.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/mtl/Clone.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/Solver.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/mtl/Heap.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/mtl/Alg.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/utils/Options.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/utils/../mtl/IntTypes.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/utils/../mtl/Vec.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/utils/ParseUtils.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/SolverTypes.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/../mtl/IntTypes.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/../mtl/Alg.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/../mtl/Vec.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/../mtl/Map.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/../mtl/../mtl/IntTypes.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/../mtl/../mtl/Vec.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/../mtl/Alloc.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/../mtl/XAlloc.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/../mtl/Vec.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/BoundedQueue.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/Constants.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/SolverStats.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/map.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/mapf.h
/mnt/c/Users/marti/Desktop/school/dp/smt_cbs/solver.o /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/solver.or /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/solver.od /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/solver.op: /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/solver.cc \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/utils/System.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/utils/../mtl/IntTypes.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/mtl/Sort.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/mtl/Vec.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/mtl/IntTypes.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/mtl/XAlloc.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/Constants.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/Solver.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/mtl/Heap.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/mtl/Alg.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/mtl/Clone.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/utils/Options.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/utils/../mtl/Vec.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/utils/ParseUtils.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/SolverTypes.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/../mtl/IntTypes.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/../mtl/Alg.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/../mtl/Vec.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/../mtl/Map.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/../mtl/../mtl/IntTypes.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/../mtl/../mtl/Vec.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/../mtl/Alloc.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/../mtl/XAlloc.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/../mtl/Vec.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/BoundedQueue.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/SolverStats.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/map.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/SimpSolver.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/mtl/Queue.h
/mnt/c/Users/marti/Desktop/school/dp/smt_cbs/SimpSolver.o /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/SimpSolver.or /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/SimpSolver.od /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/SimpSolver.op: /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/SimpSolver.cc \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/mtl/Sort.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/mtl/Vec.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/mtl/IntTypes.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/mtl/XAlloc.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/utils/System.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/utils/../mtl/IntTypes.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/SimpSolver.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/mtl/Queue.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/mtl/Clone.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/Solver.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/mtl/Heap.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/mtl/Alg.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/utils/Options.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/utils/../mtl/Vec.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/utils/ParseUtils.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/SolverTypes.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/../mtl/IntTypes.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/../mtl/Alg.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/../mtl/Vec.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/../mtl/Map.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/../mtl/../mtl/IntTypes.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/../mtl/../mtl/Vec.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/../mtl/Alloc.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/../mtl/XAlloc.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/../mtl/Vec.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/BoundedQueue.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/Constants.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/SolverStats.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/map.h
/mnt/c/Users/marti/Desktop/school/dp/smt_cbs/mapf.o /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/mapf.or /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/mapf.od /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/mapf.op: /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/mapf.cc \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/Solver.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/mtl/Heap.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/mtl/Vec.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/mtl/IntTypes.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/mtl/XAlloc.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/mtl/Alg.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/mtl/Clone.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/utils/Options.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/utils/../mtl/IntTypes.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/utils/../mtl/Vec.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/utils/ParseUtils.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/SolverTypes.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/../mtl/IntTypes.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/../mtl/Alg.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/../mtl/Vec.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/../mtl/Map.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/../mtl/../mtl/IntTypes.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/../mtl/../mtl/Vec.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/../mtl/Alloc.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/../mtl/XAlloc.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/../mtl/Vec.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/BoundedQueue.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/Constants.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/glucose/core/SolverStats.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/map.h \
 /mnt/c/Users/marti/Desktop/school/dp/smt_cbs/mapf.h
